name: apn_fb_login_example
description: Demonstrates how to use the apn_fb_login plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  apn_fb_login:
    path: ../

flutter:
  uses-material-design: true
