name: apn_fb_login
description: Flutter Facebook Plugin.
version: 0.0.8
author: Mark Mooibroek <mark@appnormal.com>
homepage: https://github.com/markmooibroek/apn_fb_login

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.appnormal.plugin.fblogin
    pluginClass: ApnFbLoginPlugin
